# Generated by Django 3.0.4 on 2020-03-26 12:47

from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('raft', '0007_auto_20200326_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('form_required', models.BooleanField(default=True)),
                ('picture_path', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'raft_category',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price_currency', djmoney.models.fields.CurrencyField(choices=[('VND', 'Dong'), ('USD', 'US Dollar')], default='VND', editable=False, max_length=3)),
                ('price', djmoney.models.fields.MoneyField(decimal_places=0, default_currency='VND', max_digits=19)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Category')),
                ('contacts', models.ManyToManyField(blank=True, to='raft.Contact')),
            ],
            options={
                'db_table': 'raft_service',
            },
        ),
    ]
