# Generated by Django 3.0.4 on 2020-04-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='last_active',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
