# Generated by Django 3.0.4 on 2020-04-03 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_squashed_0008_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='key',
        ),
    ]
