# Generated by Django 3.0.4 on 2020-04-03 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_message_key'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
