# Generated by Django 3.0.4 on 2020-04-07 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20200407_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='last_active',
        ),
    ]
