# Generated by Django 3.0.4 on 2020-04-07 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_room_last_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='last_active',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
