# Generated by Django 3.0.4 on 2020-04-04 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='last_active',
            field=models.TimeField(auto_now=True),
        ),
    ]
