# Generated by Django 3.0.4 on 2020-03-15 13:22

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('raft', '0002_auto_20200315_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='picture_path',
            field=models.CharField(default='web.png', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=0, default_currency='VND', max_digits=19),
        ),
    ]
