# Generated by Django 3.0.4 on 2020-03-20 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raft', '0005_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='services', to='raft.Service'),
        ),
        migrations.AddField(
            model_name='service',
            name='contacts',
            field=models.ManyToManyField(blank=True, to='raft.Contact'),
        ),
    ]
