# Generated by Django 3.0.4 on 2020-03-26 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raft', '0006_auto_20200320_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='category',
        ),
        migrations.RemoveField(
            model_name='service',
            name='contacts',
        ),
    ]
