# Generated by Django 3.0.4 on 2020-03-26 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        ('raft', '0007_auto_20200326_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='services', to='services.Service'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
